name: CI

on: [push]

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    secrets: inherit #https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idsecretsinherit
   
  sca:
    needs: build
    name: SCA
    uses: ./.github/workflows/sca.yml
    secrets: inherit
    
  sast_scan:
   name: Run Bandit Scan
   runs-on: ubuntu-latest

   steps:
   - name: Checkout code
     uses: actions/checkout@v2

   - name: Set up Python
     uses: actions/setup-python@v2
     with:
       python-version: 3.8

   - name: Install Bandit
     run: pip install bandit

   - name: Run Bandit Scan
     run: bandit -ll -ii -r . -f json -o bandit-report.json

   - name: Upload Artifact
     uses: actions/upload-artifact@v3
     if: always()
     with:
      name: bandit-findings
      path: bandit-report.json
      

   - name: Upload Artifact
     uses: actions/upload-artifact@v3
     if: always()
     with:
       name: docker-scout-findings
       path: scout-report.sarif

  docker:
    needs: build
    name: Build docker
    uses: ./.github/workflows/docker.yml
    secrets: inherit

  container-image-scan:
    needs: docker
    name: Build docker image
    uses: ./.github/workflows/container-image-scan.yml
    secrets: inherit
    with:
      image-tag: ${{ needs.docker.outputs.image-tag }}

  dast:
    needs: [build,docker]
    name: DAST Scan
    uses: ./.github/workflows/dast.yml
    secrets: inherit
    with:
      image-tag: ${{ needs.docker.outputs.image-tag }}
 


   

   
